"""Response-related Pydantic schemas."""

from datetime import datetime
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from baymax.core.enums import ResponseStrategy


class RespondRequest(BaseModel):
    """Request schema for generating a supportive response."""

    session_id: UUID
    user_id: UUID | None = None
    context: str = Field(default="", description="Optional context about current interaction.")


class SupportiveResponse(BaseModel):
    """A supportive response generated by the system."""

    id: UUID = Field(default_factory=uuid4)
    session_id: UUID
    user_id: UUID | None = None
    strategy: ResponseStrategy
    message: str
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    evidence_refs: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)
    memory_refs: list[str] = Field(
        default_factory=list,
        description="Content of memories used to generate this response.",
    )
    state_summary: dict[str, str] = Field(
        default_factory=dict,
        description="Snapshot of session state at response time.",
    )
    # --- Iteration 005: Grounded dialogue metadata ---
    backend: str = Field(
        default="rule_based",
        description="Dialogue backend that generated this response.",
    )
    model_name: str = Field(
        default="",
        description="Model name used by the backend.",
    )
    fallback_used: bool = Field(
        default=False,
        description="Whether the rule-based fallback was used instead of the primary backend.",
    )
    safety_flags: list[str] = Field(
        default_factory=list,
        description="Safety flags raised during response generation.",
    )
    tool_usage: list[str] = Field(
        default_factory=list,
        description="Tool names used to produce this response.",
    )
    source_refs: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Structured source references used in this response.",
    )


# --- Iteration 005: New schemas ---


class DialogueBackendInfo(BaseModel):
    """Information about available dialogue backends and active configuration."""

    available_backends: list[str] = Field(
        description="All backends that have been implemented.",
    )
    active_backend: str = Field(
        description="Currently configured backend.",
    )
    active_model: str = Field(
        description="Currently configured model name (empty for rule_based).",
    )
    fallback_enabled: bool = Field(
        description="Whether rule-based fallback is enabled.",
    )


class GroundedPromptContext(BaseModel):
    """Packaged context used to build a grounded prompt for the LLM."""

    user_id: UUID | None = None
    user_display_name: str | None = None
    session_id: UUID
    strategy: ResponseStrategy
    state_summary: dict[str, str] = Field(default_factory=dict)
    memory_refs: list[str] = Field(
        default_factory=list,
        description="Retrieved memory contents to include in the prompt.",
    )
    recent_turns: list[dict] = Field(
        default_factory=list,
        description="Recent conversation turns: [{role, text, timestamp}]",
    )
    safety_rules: list[str] = Field(default_factory=list)
    context: str = ""
    top_k_memories: int = 5
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    # Iteration 009 - affect context for tone adjustment
    affect_context: str = Field(
        default="",
        description="Optional affect-based tone guidance (internal use only)"
    )


class SafetyDecision(BaseModel):
    """Result of a safety check on the user context or LLM output."""

    is_safe: bool
    flags: list[str] = Field(default_factory=list)
    redirect_response: str | None = Field(
        default=None,
        description="Pre-composed safe redirect message when is_safe=False.",
    )


class DialogueDebugTrace(BaseModel):
    """Debug trace for a single dialogue generation call."""

    backend: str
    model_name: str
    prompt_tokens_approx: int = 0
    latency_ms: float = 0.0
    raw_output: str | None = None
    fallback_used: bool = False
    safety_flags: list[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class GroundedResponse(BaseModel):
    """Full structured output from the grounded dialogue pipeline."""

    text: str
    strategy: ResponseStrategy
    memory_refs: list[str] = Field(default_factory=list)
    state_summary: dict[str, str] = Field(default_factory=dict)
    backend: str = "rule_based"
    model_name: str = ""
    fallback_used: bool = False
    safety_flags: list[str] = Field(default_factory=list)
    debug: DialogueDebugTrace | None = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class DialogueSmokeTestResult(BaseModel):
    """Result of a single dialogue smoke-test case."""

    case: str
    backend: str
    result: str = Field(description="passed|failed|not_run|ambiguous")
    notes: str = ""
    response_text: str | None = None
    memory_refs: list[str] = Field(default_factory=list)
    latency_ms: float = 0.0
    timestamp: datetime = Field(default_factory=datetime.utcnow)
