"""Response-related Pydantic schemas."""

from datetime import datetime
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from baymax.core.enums import ResponseStrategy


class RespondRequest(BaseModel):
    """Request schema for generating a supportive response."""

    session_id: UUID
    user_id: UUID | None = None
    context: str = Field(default="", description="Optional context about current interaction.")


class SupportiveResponse(BaseModel):
    """A supportive response generated by the system."""

    id: UUID = Field(default_factory=uuid4)
    session_id: UUID
    user_id: UUID | None = None
    strategy: ResponseStrategy
    message: str
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    evidence_refs: list[str] = Field(default_factory=list)
    metadata: dict[str, str] = Field(default_factory=dict)
